### ISSUE TITLE
Missing "Load Negative"

### ISSUE THREAD

**Issue by Tobe2d** [Franck-Demongin/NX_ComfyUI_Workflow#1]
It is showing some node is mising "Load Negative" and ComfyUI_Managers cant find it.

![image](https://github.com/Franck-Demongin/NX_ComfyUI_Workflow/assets/4099839/42ec980b-b0fe-4b36-99eb-75480023ff96)

Could you guide me on this node?

**Comment by Franck-Demongin** [comment]
You're right! The "Load Negative" node comes from "https://github.com/PCMonsterx/ComfyUI-CSV-Loader", a node that is not present in ComfyUI Manager. 
Install it or replace it with a text node

**Comment by Franck-Demongin** [comment]
A new version is online. This node is replace by a simple text node.

**Comment by Franck-Demongin** [comment]
A new version is online. This node is replace by a simple text node.
